### ISSUE TITLE
Irrelevant TAS topic

### ISSUE THREAD

**Issue by Makonede** [moocf/tas-lock.java#1]
The TAS topic is for tool-assisted speedrunning, not test-and-set. This tag should be removed from the repository.

**Comment by wolfram77** [comment]
@Makonede TAS can stand for a bunch of things, as you might guess. Check the book - The Art of Multiprocessor programming by Maurice Herlihy and Nir Shavit, for TAS, TTAS locks.

**Comment by Makonede** [comment]
@wolfram77 Read https://github.com/topics/tas, the topic is for tool-assisted speedrunning.

**Comment by wolfram77** [comment]
Ok, take it. I see you have raised issues in other repos as well.
